### ISSUE TITLE
How many frames can you process in one second

### ISSUE THREAD

**Issue by MingRongXi** [saswat0/License-Plate-Recognition#4]
Hi, saswat0. Thank you for your work, it's pretty! I want to ask you some problem. My environment is 8g GRID M10-8Q, with only one graphics card. If I use darknet and tensorflow compiled with gpu at the same time, the program will report an error: 
       **Princess finished with exit code 137 (interrupted by signal 9: SIGKILL).**
So my plate-detection is so slow, but vehicle detection and ocr are fast. Have you encountered such a problem, and how many frames can you process in one second?

**Comment by saswat0** [comment]
Hi @MingRongXi 
This signal kill is most probably due to insufficient GPU memory. Try running it in CPU instead (enable openmp in the darknet makefile for multiprocessing).
The license plate detection is carried out by wpod-net and it's keras implementation is laggy. Vehicle detection and ocr are YOLO models and hence faster.
I was able to achieve a FPS of 4 in my i7, 32G (no GPU) system

**Comment by MingRongXi** [comment]
Thank you！I try it again.
